Update zmpurgelist

diff --git a/zmpurgelist b/zmpurgelist
--- a/zmpurgelist
+++ b/zmpurgelist
@@ -5,7 +5,6 @@
 # current mailbox server
 #
 # Author: rsilveira1987@live.com
-# https://github.com/rsilveira1987
 #
 ##############################################
 
@@ -13,7 +12,7 @@
 # helper functions
 ##############################################
 function usage(){
-	MSG="Usage: $(basename $0) [-h|--help]"
+	MSG="Usage: $(basename $0) -h"
 	echo "$MSG"
 }
 
@@ -21,13 +20,10 @@ function display_help(){
 	echo ""
 	usage
 	echo ""
-	echo " List all zimbra purgeable accounts in the current mailbox server"
+	echo " List all purgeable accounts in the current mailbox server"
 	echo ""
 }
 	
-# get argc value
-argc=$#
-
 # CLI options
 while test -n "$1"
 do
@@ -36,12 +32,12 @@ do
  		  display_help
 		  exit 0
 		;;
+		*)
+		echo "Invalid option: $1"
+		exit 1
 	esac
 shift
 done
-
-# validate argc number
-[ "$argc" -gt 0 ] && { usage; exit 1; }
 
 ##############################################
 # initialization
@@ -68,35 +64,35 @@ if [ $u != ${zimbra_user} ]; then
 	exit 1
 fi
 
-# compares info from mailbox accounts (inside mariadb) with ldap zimbraMailHost attribute
-# 1. get all maria db accounts ID
-# 2. search the current zimbraMailHost and zimbraMailDeliveryAddress attributes for each ID
+# compares info from mailbox accounts (inside mariadb) with ldap account zimbraMailHost attribute
+# 1. get all maria db mailbox accounts IDs
+# 2. search the current zimbraMailHost and mail info for each ID using
 # 3. compares it with current hostname info
 for i in $(/opt/zimbra/bin/mysql --batch --skip-column-names -e "select account_id from mailbox" zimbra);
 do
 	# get ldap info for each zimbraId
 	/usr/bin/ldapsearch -x -h ${ldap_host} -D ${zimbra_ldap_userdn} -w ${zimbra_ldap_password} -LLL zimbraId=$i zimbraMailHost zimbraMailDeliveryAddress > $TMP_FILE
-	
+
 	# check if a valid ldap response was given
-        #
-        # TODO: inconsistent accounts handler
-        #
-        isValid=$(/usr/bin/grep "dn:" $TMP_FILE -c)
-        if [ $isValid -eq 0 ]; then
-                # echo "Error: invalid response from ${ldap_host}" 1>&2
-                # exit 1
-                continue
-        fi
+	#
+	# TODO: inconsistent accounts handler
+	#
+	isValid=$(/usr/bin/grep "dn:" $TMP_FILE -c)
+	if [ $isValid -eq 0 ]; then
+		#echo "Error: invalid response from ${ldap_host}" 1>&2
+		#exit 1
+		continue # skipping
+	fi
 	
 	# get account mail delivery address
-	mail=$(/usr/bin/cat $TMP_FILE | /usr/bin/grep -i zimbraMailDeliveryAddress | awk '{print $2}')
+	account=$(/usr/bin/cat $TMP_FILE | /usr/bin/grep -i zimbraMailDeliveryAddress | awk '{print $2}')
 
 	# check if need purge
 	needToClear=$(/usr/bin/grep ${zimbra_server_hostname} $TMP_FILE -c)
 
 	# inverted logic
 	if [ $needToClear -eq 0 ]; then
-		echo "$mail";
+		echo "$account";
 	fi
 done
 
